/**
 * Local, provisional copy of the v2 contracts (sections 8, 9, 10 and 11 of
 * INSTRUCTIONS.md, at the repo root). The source of truth is `contracts/`, owned by
 * Member 3; see README, "Still to agree with Member 3".
 * Don't rename enums here without the team's agreement.
 */
import { z } from "zod";

export const SCHEMA_VERSION = "2.0" as const;
export const SchemaVersion = z.literal(SCHEMA_VERSION);

/** Limits per call or SMS conversation (section 17): the initial assessment + 3 rounds, and 5 questions. */
export const MAX_ASSESSMENTS = 4;
export const MAX_QUESTIONS = 5;

// --- Primitives (section 8) ---

/** E.164: "+" followed by 2 to 15 digits, no leading zero. */
export const PhoneE164 = z.string().regex(/^\+[1-9]\d{1,14}$/, "must be in E.164 format");

/** ISO 8601 date in UTC (Z suffix required). */
export const IsoUtc = z.iso.datetime({ offset: false });

/** Opaque ID generated by the backend. */
export const OpaqueId = z.string().min(1).max(128);

export const Language = z.string().min(2).max(16);

// --- Enums (sections 9, 10 and 11) ---

export const Disposition = z.enum(["ask_more", "advise", "refer"]);
export const EvidenceQuality = z.enum(["insufficient", "low", "medium", "high"]);
export const Urgency = z.enum(["unknown", "routine", "soon", "urgent"]);
export const Channel = z.enum(["voice", "sms", "operator"]);
export const Completeness = z.enum(["partial", "sufficient"]);
export const ProcessingStatus = z.enum(["pending", "processed", "failed"]);
export const MeasurementSource = z.enum(["farmer_reported", "sensor", "technician"]);
export const DataFreshness = z.enum(["fresh", "stale", "unknown"]);

export const CaseStatus = z.enum(["reported", "suspected", "confirmed", "monitoring", "resolved"]);
export const FollowupStatus = z.enum(["scheduled", "contacting", "responded", "no_response", "failed", "cancelled"]);

// --- Enums new in v2 (sections 9, 10.1 and 10.4) ---

export const AnswerType = z.enum(["yes_no", "number_with_unit", "choice", "free_text"]);
export const StatusReported = z.enum(["worse", "same", "improved", "resolved", "unknown"]);
export const ActionWorked = z.enum(["yes", "no", "partial", "unknown"]);
export const ResolutionVerification = z.enum(["farmer_reported", "verified", "disputed"]);

// --- Measurement (section 9) ---

export const Measurement = z.strictObject({
  name: z.string().min(1),
  /** null = unknown; never replaced with zero. */
  value: z.union([z.number(), z.string()]).nullable(),
  unit: z.string().min(1),
  /** soil, irrigation water or other; the spec doesn't fix an enum. */
  sample_type: z.string().min(1),
  measured_at: IsoUtc.nullable(),
  method: z.string().nullable(),
  source: MeasurementSource,
});

// --- Uniform error (section 8) ---

export const ErrorDetail = z.strictObject({
  field: z.string(),
  reason: z.string(),
});

export const ErrorBody = z.strictObject({
  error: z.strictObject({
    code: z.string(),
    message: z.string(),
    retryable: z.boolean(),
    request_id: z.string(),
    details: z.array(ErrorDetail),
  }),
});

// --- Outbox event (section 11) ---

export const EventType = z.enum([
  "report.created",
  "assessment.completed",
  "env.summary_refreshed",
  "risk_model.activated",
  "risk.updated",
  "alert.approved",
  "notification.status_changed",
  "followup.due",
  "followup.responded",
  "case.resolved",
]);

export const OutboxEvent = z.strictObject({
  event_id: OpaqueId,
  schema_version: SchemaVersion,
  event_type: EventType,
  occurred_at: IsoUtc,
  aggregate_id: OpaqueId,
  aggregate_version: z.number().int().min(1),
  correlation_id: z.string().nullable(),
  is_demo: z.boolean(),
  payload: z.record(z.string(), z.unknown()),
});

export type ErrorDetail = z.infer<typeof ErrorDetail>;
export type ErrorBody = z.infer<typeof ErrorBody>;
export type CaseStatus = z.infer<typeof CaseStatus>;
export type FollowupStatus = z.infer<typeof FollowupStatus>;
export type StatusReported = z.infer<typeof StatusReported>;
export type ActionWorked = z.infer<typeof ActionWorked>;
export type ResolutionVerification = z.infer<typeof ResolutionVerification>;
